In [5]:
# import the cv2 library
import cv2

# The function cv2.imread() is used to read an image.
img = cv2.imread('D:/EntornosPython/imgs/cell.png')
#img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# The function cv2.imshow() is used to display an image in a window.
cv2.imshow('BGR image',img)

# waitKey() waits for a key press to close the window and 0 specifies indefinite loops
cv2.waitKey(0)

# cv2.destroyAllWindows() simply destroys all the windows we created.
cv2.destroyAllWindows()

# The function cv2.imwrite() is used to write an image.
#cv2.imwrite('grayscale.jpg',img_grayscale)

In [6]:
b, g, r = cv2.split (img) # El orden es b, g, r, no r, g, b
merged = cv2.merge([b,g,r])

cv2.imshow('image',img)
cv2.imshow("Blue 1", b)
cv2.imshow("Green 1", g)
cv2.imshow("Red 1", r)
cv2.imshow("merged 1", merged)
cv2.waitKey (0) #Asegúrese de agregar cv2.waitKey (0), de lo contrario se informará un error
cv2.destroyAllWindows()

In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [7]:
print(img.shape)
h,w,c = img.shape


(424, 259, 3)


In [1]:
def rgb_to_hsv(r, g, b):
    r = float(r)
    g = float(g)
    b = float(b)
    high = max(r, g, b)
    low = min(r, g, b)
    h, s, v = high, high, high

    d = high - low
    s = 0 if high == 0 else d/high

    if high == low:
        h = 0.0
    else:
        h = {
            r: ((g - b) / d) % 6,
            g: (b - r) / d + 2,
            b: (r - g) / d + 4,
        }[high]
        h /= 6

    return h, s, v

In [9]:
resutlHSVown = img.copy()

In [2]:
def HSVown(img,resutlHSVown,h,w):
    for i in range(h):
        for j in range(w):
            b = img[i][j][0]
            g = img[i][j][1]
            r = img[i][j][2]
            h,s,v = rgb_to_hsv(r,g,b)
            #print(h)
            resutlHSVown[i][j][0] = h
            resutlHSVown[i][j][1] = s
            resutlHSVown[i][j][2] = v

In [10]:

h,s,v = cv2.split (resutlHSVown)
merged = cv2.merge([h,s,v])

cv2.imshow("Hue 1", h)
cv2.imshow("Saturation 1", s)
cv2.imshow("Valor 1", v)
cv2.imshow("merged 1", merged)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:

hsvImg = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split (hsvImg)
merged = cv2.merge([h,s,v])

cv2.imshow("Hue 1", h)
cv2.imshow("Saturation 1", s)
cv2.imshow("Valor 1", v)
cv2.imshow("merged 1", merged)


#cv2.imshow('RGB image', img)
#cv2.imshow('HSV image', hsvImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Propuestas de algoritmos de HSV

### Imagen con Niebla

In [3]:
from skimage.color import rgb2hsv
from skimage.util import img_as_float64
import cv2

In [4]:
img = cv2.imread('D:/EntornosPython/imgs/Middlebury_Hazy/Backpack_Hazy.bmp')

print(img.shape)
# let's downscale the image using new  width and height
down_width = 735
down_height = 504
down_points = (down_width, down_height)
img_resized = cv2.resize(img, down_points, interpolation= cv2.INTER_LINEAR)
print(img_resized.shape)


(2016, 2940, 3)
(504, 735, 3)


In [5]:
# Convert to HSV colour space
## HSV ONW
resutlHSVown = img_resized.copy()
h,w,c = img_resized.shape
HSVown(img_resized,resutlHSVown,h,w)    


## HSV openCV
resultCV = cv2.cvtColor(img_resized, cv2.COLOR_BGR2HSV)

# HSV Skimage
img_resized = img_as_float64(img_resized)
resultSkimage = rgb2hsv(img_resized)


cv2.imshow("Image Original",img_resized)
cv2.imshow("HSV using skimage",resultSkimage)
cv2.imshow("HSV using openCV",resultCV)
cv2.imshow("HSV using my own implementation",resutlHSVown)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [60]:
channel_H,channel_S,channel_V = cv2.split (resultCV)
merged = cv2.merge([channel_H,channel_S,channel_V])

cv2.imshow("Hue 1", channel_H)
cv2.imshow("Saturation 1", channel_S)
cv2.imshow("Valor 1", channel_V)
cv2.imshow("merged 1", merged)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Imagen Ground Truth

In [7]:
imgReal = cv2.imread('D:/EntornosPython/imgs/Middlebury_GT/Backpack_im0.png')
print(imgReal.shape)
# let's downscale the image using new  width and height
down_width = 735
down_height = 504
down_points = (down_width, down_height)
img_resizedReal = cv2.resize(imgReal, down_points, interpolation= cv2.INTER_LINEAR)
print(img_resizedReal.shape)


(2016, 2940, 3)
(504, 735, 3)


In [8]:
# Convert to HSV colour space
## HSV ONW
resutlHSVownReal = img_resizedReal.copy()
h,w,c = img_resizedReal.shape
HSVown(img_resizedReal,resutlHSVownReal,h,w)    


## HSV openCV
resultCVReal = cv2.cvtColor(img_resizedReal, cv2.COLOR_BGR2HSV)

# HSV Skimage
img_resizedReal = img_as_float64(img_resizedReal)
resultSkimageReal = rgb2hsv(img_resizedReal)


cv2.imshow("Image Original",img_resizedReal)
cv2.imshow("HSV using skimage",resultSkimageReal)
cv2.imshow("HSV using openCV",resultCVReal)
cv2.imshow("HSV using my own implementation",resutlHSVownReal)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
channelReal_H,channelReal_S,channelReal_V = cv2.split (resultCVReal)
mergedReal = cv2.merge([channelReal_H,channelReal_S,channelReal_V])

cv2.imshow("Hue 1", channelReal_H)
cv2.imshow("Saturation 1", channelReal_S)
cv2.imshow("Valor 1", channelReal_V)
cv2.imshow("merged 1", mergedReal)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Comparacion entre del canales HUE,Valor,Saturacion de las imágenes con niebla y las imágenes reales.

### Separacion de canales en imagen con niebla

In [10]:
cv2.imshow("Hue Ground Truth", channelReal_H)
cv2.imshow("Hue Hazy", channel_H)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [63]:
cv2.imshow("Value Ground Truth", channelReal_V)
cv2.imshow("Value Hazy", channel_V)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
cv2.imshow("Saturation Ground Truth", channelReal_S)
cv2.imshow("Saturation Hazy", channel_S)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
from skimage.metrics import structural_similarity as ssim
import numpy as np

In [12]:

# Compute SSIM between two images
(score, diff) = ssim(channelReal_H, channel_H, full=True)
#print("Image similarity", score)
print("SSIM: {}".format(score))


SSIM: 0.9870807377968952


In [13]:
# The diff image contains the actual image differences between the two images
# and is represented as a floating point data type in the range [0,1] 
# so we must convert the array to 8-bit unsigned integers in the range
# [0,255] before we can use it with OpenCV
diff = (diff * 255).astype("uint8")

# Threshold the difference image, followed by finding contours to
# obtain the regions of the two input images that differ
thresh = cv2.threshold(diff, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]

cv2.imshow('before', channelReal_H)
cv2.imshow('after', channel_H)
cv2.imshow('diff',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

## INTENSITY RECOVERY BY OPENING OPERATION

In [14]:
imgBackpack = cv2.imread('D:/EntornosPython/imgs/Middlebury_Hazy/Backpack_Hazy.bmp')

print(img.shape)
# let's downscale the image using new  width and height
down_width = 735
down_height = 504
down_points = (down_width, down_height)
img_resizedB = cv2.resize(imgBackpack, down_points, interpolation= cv2.INTER_LINEAR)
print(img_resizedB.shape)

cv2.imshow('Ground Truth',img_resizedB )
cv2.waitKey(0)
cv2.destroyAllWindows()


(2016, 2940, 3)
(504, 735, 3)


### Calculate minimum value in RGB channels

<img src="../imgs/formula/minimumchannel.png">

In [15]:
def getMinChannel(img):
    if len(img.shape)==3 and img.shape[2]==3:
        pass
    else:
        print("bad image shape, input must be color image")
        return None
    
    return np.min(img, axis=2)

In [16]:
minChannel = getMinChannel(img_resizedB)
cv2.imshow('minChannel',minChannel )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
print(img_resizedB[0][0])
print(minChannel[0][0])

[216 238 248]
216


### Calculate Dark Channel Prior

In [28]:
def getDarkChannel(img,blockSize = 3):

    
    if len(img.shape)==2:
        pass
    else:
        print("bad image shape, input image must be two demensions")
        return None

    
    if blockSize % 2 == 0 or blockSize < 3:
        print('blockSize is not odd or too small')
        return None

    # addSize
    A = int((blockSize-1)/2) #AddSize

    #New height and new width
    H = img.shape[0] + blockSize - 1
    W = img.shape[1] + blockSize - 1

    # 中间结果
    imgMiddle = 255 * np.ones((H,W))    

    imgMiddle[A:H-A, A:W-A] = img
    
    imgDark = np.zeros_like(img, np.uint8)    
    
    localMin = 255
    for i in range(A, H-A):
        for j in range(A, W-A):
            x = range(i-A, i+A+1)
            y = range(j-A, j+A+1)
            imgDark[i-A,j-A] = np.min(imgMiddle[x,y])                            
            
    return imgDark

In [29]:
print(minChannel.dtype)
print(minChannel.shape)


uint8
(504, 735)


In [30]:
DCPimage = getDarkChannel(minChannel,15)
print(DCPimage)
cv2.imshow('DCPimage ',DCPimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[213 214 213 ... 186 188 192]
 [213 213 214 ... 189 186 188]
 [213 213 213 ... 187 189 186]
 ...
 [201 196 199 ... 189 187 180]
 [205 201 196 ... 183 189 187]
 [211 205 201 ... 188 183 189]]


### Compare minimun value and DCP

In [31]:
cv2.imshow('Minimumimage ',minChannel)
cv2.imshow('DCPimage ',DCPimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Modified morphological opening operation to Imin.

<img src="../imgs/formula/modifiedoperationmodificada.png">

In [32]:
#regla de 3 simple es (13,7)
  
kernelR1 = np.ones((7,7), np.uint8)  
img_erosion = cv2.erode(minChannel, kernelR1, iterations=1)  

kernelR2 = np.ones((13,13), np.uint8)  
img_dilation = cv2.dilate(img_erosion, kernelR2, iterations=1)


In [33]:
img_open = img_dilation.copy()

In [34]:
def slightest(img1,img2):
    if len(img1.shape)==2 and len(img2.shape)==2:
        pass
    else:
        print("bad image shape, input must be gray image")
        return None
    return np.minimum(img1,img2)

In [35]:
Imodify = slightest(minChannel,img_open)

In [36]:
print(minChannel)
print(img_open)
print(Imodify)

[[216 214 217 ... 186 188 192]
 [216 214 216 ... 189 190 193]
 [215 215 216 ... 187 190 194]
 ...
 [205 203 215 ... 196 187 180]
 [205 201 196 ... 183 196 198]
 [211 213 212 ... 188 188 190]]
[[214 214 214 ... 185 185 185]
 [214 214 214 ... 185 185 185]
 [214 214 214 ... 185 185 185]
 ...
 [197 197 197 ... 189 189 189]
 [197 197 197 ... 189 189 189]
 [197 197 197 ... 189 189 189]]
[[214 214 214 ... 185 185 185]
 [214 214 214 ... 185 185 185]
 [214 214 214 ... 185 185 185]
 ...
 [197 197 197 ... 189 187 180]
 [197 197 196 ... 183 189 189]
 [197 197 197 ... 188 188 189]]


In [56]:
cv2.imshow('Min Channel', minChannel)
cv2.imshow('Erosion', img_erosion)
cv2.imshow('Dilation', img_dilation)
cv2.imshow('slightestImg', Imodify)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Obtain global atmospheric light

<img src="../imgs/formula/atmosfericLight.png">

<img src="../imgs/formula/get10percent.png">


In [54]:
class Node(object):
    def __init__(self,x,y,value):
        self.x = x
        self.y = y
        self.value = value

    def printInfo(self):
        print('%s:%s:%s' %(self.x,self.y,self.value))

def getAtomsphericLight(darkChannel,img,meanMode = False, percent = 0.001):
    
    size = darkChannel.shape[0]*darkChannel.shape[1]
    height = darkChannel.shape[0]
    width = darkChannel.shape[1]

    nodes = []

    #
    for i in range(height):
        for j in range(width):
            oneNode = Node(i,j,darkChannel[i,j])
            nodes.append(oneNode)	

    #
    nodes = sorted(nodes, key = lambda node: node.value,reverse = True)
    # print(nodes[0].value)
    # print(nodes[1].value)
    # print(nodes[2].value)
    # print(nodes[3].value)
    # print(nodes[4].value)
    # print(nodes[len(nodes)-1].value)

    atomsphericLight = 0

    # #
    if int(percent*size) == 0:
        for i in range(3):
            if img[nodes[0].x,nodes[0].y,i] > atomsphericLight:
                atomsphericLight = img[nodes[0].x,nodes[0].y,i]
        return atomsphericLight

    # #
    # if meanMode:
    #     sum = 0
    #     for i in range(0,int(percent*size)):
    #         for j in range(0,3):
    #             sum = sum + img[nodes[i].x,nodes[i].y,j]
    #     atomsphericLight = int(sum/(int(percent*size)*3))
    #     return atomsphericLight

    #0.1%(percent)
    for i in range(int(percent*size)):
        for j in range(3):
            if img[nodes[i].x,nodes[i].y,j] > atomsphericLight:
                atomsphericLight = img[nodes[i].x,nodes[i].y,j]
    return atomsphericLight

In [112]:
# atomspheric Light
A_ = getAtomsphericLight(Imodify,img_resizedB, percent = 0.1)
print(A_)

255


### Obtain the Transmision Map

<img src="../imgs/formula/TransmisionMap.png">

In [145]:
imgDark = np.float64(Imodify)
omega = 0.9 #ω is used to preserve distant haze, usually fixed as 0.9.
transmission = 1 - (omega * (imgDark / A_))
transmission_for_Saturation = transmission.copy()

In [146]:
print(transmission)

[[0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 ...
 [0.30470588 0.30470588 0.30470588 ... 0.33294118 0.34       0.36470588]
 [0.30470588 0.30470588 0.30823529 ... 0.35411765 0.33294118 0.33294118]
 [0.30470588 0.30470588 0.30470588 ... 0.33647059 0.33647059 0.33294118]]


### Recover the value channel (Value)

<img src="../imgs/formula/RecoverIntensity.png">

In [147]:
t0 = 0.1
transmission[transmission<t0] = t0


In [148]:
print(transmission)

[[0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 ...
 [0.30470588 0.30470588 0.30470588 ... 0.33294118 0.34       0.36470588]
 [0.30470588 0.30470588 0.30823529 ... 0.35411765 0.33294118 0.33294118]
 [0.30470588 0.30470588 0.30470588 ... 0.33647059 0.33647059 0.33294118]]


In [149]:
channel_VFloat = np.float64(channel_V)
numeratorR = abs(channel_VFloat - A_)
denominatorR = transmission
print(channel_V.dtype)
print(channel_VFloat.dtype)
print(numeratorR.dtype)
print(denominatorR.dtype)

uint8
float64
float64
float64


In [150]:
recoValue = A_ + (numeratorR/denominatorR)
recoValue = np.uint8(recoValue)

In [151]:
print(recoValue)
cv2.imshow('channel V Retrieved', recoValue)
recoValueInv = abs(255-recoValue)
cv2.imshow('channel V Retrieved Inverso', recoValueInv)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 27  31  23 ...  45  42  36]
 [ 27  31  31 ...  39  42  33]
 [ 27  31  31 ...  42  45  33]
 ...
 [ 84  94  67 ... 116 149 147]
 [ 90 107 122 ... 143 104  98]
 [ 74  61  71 ... 123 120 122]]


In [152]:
cv2.imshow('channel V Real', channelReal_V) #canal a donde se quiere llegar (Y)
cv2.imshow('channel V Retrieved', recoValue)
cv2.imshow('channel V Retrieved Inverso', recoValueInv)
cv2.waitKey(0)
cv2.destroyAllWindows()

## SATURATION RECOVERY MODULE

<img src="../imgs/formula/Saturationrecovery.png">

The value channel in HSV color space is the maximum image of RGB.

In [153]:
print(transmission_for_Saturation.dtype)

float64


In [154]:
print(transmission_for_Saturation)

[[0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 [0.24470588 0.24470588 0.24470588 ... 0.34705882 0.34705882 0.34705882]
 ...
 [0.30470588 0.30470588 0.30470588 ... 0.33294118 0.34       0.36470588]
 [0.30470588 0.30470588 0.30823529 ... 0.35411765 0.33294118 0.33294118]
 [0.30470588 0.30470588 0.30470588 ... 0.33647059 0.33647059 0.33294118]]


In [156]:
transmission_for_Saturation = transmission_for_Saturation - 1
print(transmission_for_Saturation)

[[-0.24470588 -0.24470588 -0.24470588 ... -0.34705882 -0.34705882
  -0.34705882]
 [-0.24470588 -0.24470588 -0.24470588 ... -0.34705882 -0.34705882
  -0.34705882]
 [-0.24470588 -0.24470588 -0.24470588 ... -0.34705882 -0.34705882
  -0.34705882]
 ...
 [-0.30470588 -0.30470588 -0.30470588 ... -0.33294118 -0.34
  -0.36470588]
 [-0.30470588 -0.30470588 -0.30823529 ... -0.35411765 -0.33294118
  -0.33294118]
 [-0.30470588 -0.30470588 -0.30470588 ... -0.33647059 -0.33647059
  -0.33294118]]


In [157]:
#comprobando que V es el maximo de RGB
print(channel_V[0][0])
print(img_resized[0][0])

248
[0.84705882 0.93333333 0.97254902]


In [127]:
maximumRGB = channel_V
equation_1 = A_ * transmission_for_Saturation
equation_2 = equation_1/maximumRGB

In [128]:
print(equation_2.dtype)

float64


In [129]:
recoSaturation = channel_S * (1/(1+equation_2))
recoSaturation = np.uint8(recoSaturation)

In [130]:
cv2.imshow('channel S Retrieved', recoSaturation)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Comparacion S y S recovered

In [134]:
cv2.imshow('channel S Real', channelReal_S) #canal a donde se quiere llegar (Y)
cv2.imshow('channel S hazy', channel_S)
cv2.imshow('channel S Retrieved', recoSaturation)
cv2.waitKey(0)
cv2.destroyAllWindows()