## PROPOSED ALGORITHM

<img src="../imgs/formula/workflow.png">

In [1]:
def rgb_to_hsv(r, g, b):
    r = float(r)
    g = float(g)
    b = float(b)
    high = max(r, g, b)
    low = min(r, g, b)
    h, s, v = high, high, high

    d = high - low
    s = 0 if high == 0 else d/high

    if high == low:
        h = 0.0
    else:
        h = {
            r: ((g - b) / d) % 6,
            g: (b - r) / d + 2,
            b: (r - g) / d + 4,
        }[high]
        h /= 6

    return h, s, v

In [2]:
def HSVown(img,resutlHSVown,h,w):
    for i in range(h):
        for j in range(w):
            b = img[i][j][0]
            g = img[i][j][1]
            r = img[i][j][2]
            h,s,v = rgb_to_hsv(r,g,b)
            #print(h)
            resutlHSVown[i][j][0] = h
            resutlHSVown[i][j][1] = s
            resutlHSVown[i][j][2] = v

## Propuestas de algoritmos de HSV

### Imagen con Niebla

In [3]:
from skimage.color import rgb2hsv
from skimage.util import img_as_float64
import cv2
import numpy as np

In [4]:
#img = cv2.imread('D:/EntornosPython/imgs/Middlebury_Hazy/Piano_Hazy.bmp')
#img = cv2.imread('D:/EntornosPython/imgs/Fog/6726971629.png')
#img = cv2.imread('D:/EntornosPython/imgs/Data_Landscape/hazy/55_hazy.png')
img = cv2.imread('D:/EntornosPython/imgs/HAZY_NTIRE_2018/hazy/17_indoor_hazy.jpg')
 
print(img.shape)
# let's downscale the image using new  width and height
down_width = 705#735
down_height = 480#504
down_points = (down_width, down_height)
img_resized = cv2.resize(img, down_points, interpolation= cv2.INTER_LINEAR)
print(img_resized.shape)


(2833, 4657, 3)
(480, 705, 3)


In [5]:
print(img_resized.dtype)

uint8


In [6]:
print(img_resized)

[[[220 215 213]
  [213 207 202]
  [215 209 204]
  ...
  [195 194 196]
  [195 196 194]
  [195 196 194]]

 [[218 213 209]
  [216 211 206]
  [215 209 204]
  ...
  [193 195 196]
  [195 196 194]
  [197 194 193]]

 [[218 212 207]
  [216 210 205]
  [216 210 205]
  ...
  [195 196 194]
  [194 195 193]
  [195 195 193]]

 ...

 [[108 101  98]
  [106 100  97]
  [122 115 112]
  ...
  [ 62  60  59]
  [ 60  58  57]
  [ 60  58  58]]

 [[109 101  98]
  [108 100  97]
  [106  98  95]
  ...
  [ 60  58  58]
  [ 61  59  58]
  [ 61  59  58]]

 [[112 105 102]
  [105 100  96]
  [107 101  98]
  ...
  [ 61  59  59]
  [ 62  60  60]
  [ 63  61  61]]]


In [7]:
# Convert to HSV colour space


## HSV ONW
resutlHSVown = img_resized.copy()
h,w,c = img_resized.shape
HSVown(img_resized,resutlHSVown,h,w)    

## HSV openCV
resultCV = cv2.cvtColor(img_resized, cv2.COLOR_BGR2HSV)

# HSV Skimage
img_resizedfloat = img_as_float64(img_resized)
resultSkimage = rgb2hsv(img_resizedfloat)


cv2.imshow("Image Original",img_resized)
cv2.imshow("HSV using skimage",resultSkimage)
cv2.imshow("HSV using openCV",resultCV)
cv2.imshow("HSV using my own implementation",resutlHSVown)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [8]:
print(resultCV.dtype)

uint8


In [10]:
channel_H,channel_S,channel_V = cv2.split (resultCV)
merged = cv2.merge([channel_H,channel_S,channel_V])

cv2.imshow("Hue 1", channel_H)
cv2.imshow("Saturation 1", channel_S)
cv2.imshow("Valor 1", channel_V)
cv2.imshow("merged 1", merged)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Imagen Ground Truth

In [11]:
#imgReal = cv2.imread('D:/EntornosPython/imgs/Middlebury_GT/Piano_im0.png')
#imgReal = cv2.imread('D:/EntornosPython/imgs/Fog/827916289.png')
#imgReal = cv2.imread('D:/EntornosPython/imgs/Data_Landscape/GT/55_GT.png')
imgReal = cv2.imread('D:/EntornosPython/imgs/HAZY_NTIRE_2018/GT/17_indoor_GT.jpg')
print(imgReal.shape)

# let's downscale the image using new  width and height
down_width = 705#735
down_height = 480#504
down_points = (down_width, down_height)
img_resizedReal = cv2.resize(imgReal, down_points, interpolation= cv2.INTER_LINEAR)
print(img_resizedReal.shape)


(2833, 4657, 3)
(480, 705, 3)


In [12]:
print(img_resizedReal.dtype)

uint8


In [13]:
# Convert to HSV colour space
## HSV ONW
resutlHSVownReal = img_resizedReal.copy()
h_,w_,c_ = img_resizedReal.shape
HSVown(img_resizedReal,resutlHSVownReal,h_,w_)    


## HSV openCV
resultCVReal = cv2.cvtColor(img_resizedReal, cv2.COLOR_BGR2HSV)

# HSV Skimage
img_resizedReal = img_as_float64(img_resizedReal)
resultSkimageRealFloat = rgb2hsv(img_resizedReal)


cv2.imshow("Image Original",img_resizedReal)
cv2.imshow("HSV using skimage",resultSkimageRealFloat)
cv2.imshow("HSV using openCV",resultCVReal)
cv2.imshow("HSV using my own implementation",resutlHSVownReal)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
channelReal_H,channelReal_S,channelReal_V = cv2.split (resultCVReal)
mergedReal = cv2.merge([channelReal_H,channelReal_S,channelReal_V])

cv2.imshow("Hue 1", channelReal_H)
cv2.imshow("Saturation 1", channelReal_S)
cv2.imshow("Valor 1", channelReal_V)
cv2.imshow("merged 1", mergedReal)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Comparacion entre del canales HUE,Valor,Saturacion de las imágenes con niebla y las imágenes reales.

### Separacion de canales en imagen con niebla

In [16]:
cv2.imshow("Hue Ground Truth", channelReal_H)
cv2.imshow("Hue Hazy", channel_H)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
cv2.imshow("Value Ground Truth", channelReal_V)
cv2.imshow("Value Hazy", channel_V)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
cv2.imshow("Saturation Ground Truth", channelReal_S)
cv2.imshow("Saturation Hazy", channel_S)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
from skimage.metrics import structural_similarity as ssim

In [22]:

# Compute SSIM between two images
(score, diff) = ssim(channelReal_H, channel_H, full=True)
#print("Image similarity", score)
print("SSIM: {}".format(score))


SSIM: 0.22042788396591595


In [24]:
# The diff image contains the actual image differences between the two images
# and is represented as a floating point data type in the range [0,1] 
# so we must convert the array to 8-bit unsigned integers in the range
# [0,255] before we can use it with OpenCV
diff = (diff * 255).astype("uint8")

# Threshold the difference image, followed by finding contours to
# obtain the regions of the two input images that differ
thresh = cv2.threshold(diff, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]

cv2.imshow('before', channelReal_H)
cv2.imshow('after', channel_H)
cv2.imshow('diff',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

## INTENSITY RECOVERY BY OPENING OPERATION

In [25]:
#imgBackpack = cv2.imread('D:/EntornosPython/imgs/Middlebury_Hazy/Backpack_Hazy.bmp')

cv2.imshow('Ground Truth',img_resized )
cv2.waitKey(0)
cv2.destroyAllWindows()


### Calculate minimum value in RGB channels

<img src="../imgs/formula/minimumchannel.png">

In [26]:
def getMinChannel(img):
    if len(img.shape)==3 and img.shape[2]==3:
        pass
    else:
        print("bad image shape, input must be color image")
        return None
    
    return np.min(img, axis=2)

In [27]:
minChannel = getMinChannel(img_resized)
cv2.imshow('minChannel',minChannel)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
print(img_resized[0][0])
print(minChannel[0][0])

[220 215 213]
213


### Calculate Dark Channel Prior

In [29]:
def getDarkChannel(img,blockSize = 3):

    
    if len(img.shape)==2:
        pass
    else:
        print("bad image shape, input image must be two demensions")
        return None

    
    if blockSize % 2 == 0 or blockSize < 3:
        print('blockSize is not odd or too small')
        return None

    # addSize
    A = int((blockSize-1)/2) #AddSize

    #New height and new width
    H = img.shape[0] + blockSize - 1
    W = img.shape[1] + blockSize - 1

    # 中间结果
    imgMiddle = 255 * np.ones((H,W))    

    imgMiddle[A:H-A, A:W-A] = img
    
    imgDark = np.zeros_like(img, np.uint8)    
    
    localMin = 255
    for i in range(A, H-A):
        for j in range(A, W-A):
            x = range(i-A, i+A+1)
            y = range(j-A, j+A+1)
            imgDark[i-A,j-A] = np.min(imgMiddle[x,y])                            
            
    return imgDark

In [30]:
print(minChannel.dtype)
print(minChannel.shape)


uint8
(480, 705)


In [31]:
DCPimage = getDarkChannel(minChannel,15)
print(DCPimage)
cv2.imshow('DCPimage ',DCPimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[202 201 200 ... 193 193 194]
 [201 202 201 ... 193 193 193]
 [202 201 201 ... 192 193 193]
 ...
 [ 97  95  98 ...  58  57  57]
 [ 96  97  95 ...  58  58  57]
 [102  96  97 ...  58  58  58]]


### Compare minimun value and DCP

In [32]:
cv2.imshow('Minimumimage ',minChannel)
cv2.imshow('DCPimage ',DCPimage)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Modified morphological opening operation to Imin.

<img src="../imgs/formula/modifiedoperationmodificada.png">

In [33]:
#regla de 3 simple es (13,7) backpack
#regla de 3 simple es (13,7) Piano
  
kernelR1 = np.ones((31,31), np.uint8)  
img_erosion = cv2.erode(minChannel, kernelR1, iterations=1)  

kernelR2 = np.ones((35,35), np.uint8)  
img_dilation = cv2.dilate(img_erosion, kernelR2, iterations=1)


In [34]:
img_open = img_dilation.copy()

In [35]:
def slightest(img1,img2):
    if len(img1.shape)==2 and len(img2.shape)==2:
        pass
    else:
        print("bad image shape, input must be gray image")
        return None
    return np.minimum(img1,img2)

In [36]:
Imodify = slightest(minChannel,img_open)

In [37]:
print(minChannel)
print(img_open)
print(Imodify)

[[213 202 204 ... 194 194 194]
 [209 206 204 ... 193 194 193]
 [207 205 205 ... 194 193 193]
 ...
 [ 98  97 112 ...  59  57  58]
 [ 98  97  95 ...  58  58  58]
 [102  96  98 ...  59  60  61]]
[[199 199 199 ... 184 184 183]
 [199 199 199 ... 184 184 183]
 [199 199 199 ... 184 184 183]
 ...
 [ 97  97  97 ...  57  57  57]
 [ 97  97  97 ...  57  57  57]
 [ 96  96  96 ...  57  57  57]]
[[199 199 199 ... 184 184 183]
 [199 199 199 ... 184 184 183]
 [199 199 199 ... 184 184 183]
 ...
 [ 97  97  97 ...  57  57  57]
 [ 97  97  95 ...  57  57  57]
 [ 96  96  96 ...  57  57  57]]


In [39]:
cv2.imshow('Min Channel', minChannel)
cv2.imshow('Erosion', img_erosion)
cv2.imshow('Dilation', img_dilation)
cv2.imshow('slightestImg', Imodify)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Obtain global atmospheric light

<img src="../imgs/formula/atmosfericLight.png">

<img src="../imgs/formula/get10percent.png">


In [40]:
class Node(object):
    def __init__(self,x,y,value):
        self.x = x
        self.y = y
        self.value = value

    def printInfo(self):
        print('%s:%s:%s' %(self.x,self.y,self.value))

def getAtomsphericLight(darkChannel,img,meanMode = False, percent = 0.001):
    
    size = darkChannel.shape[0]*darkChannel.shape[1]
    height = darkChannel.shape[0]
    width = darkChannel.shape[1]

    nodes = []

    #
    for i in range(height):
        for j in range(width):
            oneNode = Node(i,j,darkChannel[i,j])
            nodes.append(oneNode)	

    #
    nodes = sorted(nodes, key = lambda node: node.value,reverse = True)
    # print(nodes[0].value)
    # print(nodes[1].value)
    # print(nodes[2].value)
    # print(nodes[3].value)
    # print(nodes[4].value)
    # print(nodes[len(nodes)-1].value)

    atomsphericLight = 0

    # #
    if int(percent*size) == 0:
        for i in range(3):
            if img[nodes[0].x,nodes[0].y,i] > atomsphericLight:
                atomsphericLight = img[nodes[0].x,nodes[0].y,i]
        return atomsphericLight

    # #
    # if meanMode:
    #     sum = 0
    #     for i in range(0,int(percent*size)):
    #         for j in range(0,3):
    #             sum = sum + img[nodes[i].x,nodes[i].y,j]
    #     atomsphericLight = int(sum/(int(percent*size)*3))
    #     return atomsphericLight

    #0.1%(percent)
    for i in range(int(percent*size)):
        for j in range(3):
            if img[nodes[i].x,nodes[i].y,j] > atomsphericLight:
                atomsphericLight = img[nodes[i].x,nodes[i].y,j]
    return atomsphericLight

In [41]:
print(img_resized.dtype)

uint8


In [42]:
# atomspheric Light
A_ = getAtomsphericLight(Imodify,img_resized, percent = 0.1)
print(A_)

255


### Obtain the Transmision Map

<img src="../imgs/formula/TransmisionMap.png">

In [43]:
imgDark = np.float64(Imodify)
omega = 0.9 #ω is used to preserve distant haze, usually fixed as 0.9.
transmission = 1 - (omega * (imgDark / A_))
transmission_for_Saturation = transmission.copy()

In [44]:
print(transmission)

[[0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 ...
 [0.65764706 0.65764706 0.65764706 ... 0.79882353 0.79882353 0.79882353]
 [0.65764706 0.65764706 0.66470588 ... 0.79882353 0.79882353 0.79882353]
 [0.66117647 0.66117647 0.66117647 ... 0.79882353 0.79882353 0.79882353]]


### Recover the value channel (Value)

<img src="../imgs/formula/RecoverIntensity.png">

In [45]:
t0 = 0.1
transmission[transmission<t0] = t0


In [46]:
print(transmission)

[[0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 ...
 [0.65764706 0.65764706 0.65764706 ... 0.79882353 0.79882353 0.79882353]
 [0.65764706 0.65764706 0.66470588 ... 0.79882353 0.79882353 0.79882353]
 [0.66117647 0.66117647 0.66117647 ... 0.79882353 0.79882353 0.79882353]]


In [47]:
channel_VFloat = np.float64(channel_V)
numeratorR = channel_VFloat - A_
denominatorR = transmission
print(channel_V.dtype)
print(channel_VFloat.dtype)
print(numeratorR.dtype)
print(denominatorR.dtype)

uint8
float64
float64
float64


In [48]:
recoValue = A_ + (numeratorR/denominatorR)
recoValue = np.uint8(recoValue)

In [49]:
print(recoValue)
cv2.imshow('channel V Retrieved', recoValue)
recoValueInv = abs(255-recoValue)
cv2.imshow('channel V Retrieved Inverso', recoValueInv)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[137 113 120 ...  86  86  88]
 [130 123 120 ...  86  86  91]
 [130 123 123 ...  86  83  85]
 ...
 [ 31  28  52 ...  13  10  10]
 [ 32  31  30 ...  10  12  12]
 [ 38  28  31 ...  12  13  14]]


In [50]:
cv2.imshow('channel V Real', channelReal_V) #canal a donde se quiere llegar (Y)
cv2.imshow('channel V Retrieved', recoValue)
cv2.imshow('channel V Retrieved Inverso', recoValueInv)
cv2.waitKey(0)
cv2.destroyAllWindows()

## SATURATION RECOVERY MODULE

<img src="../imgs/formula/Saturationrecovery.png">

The value channel in HSV color space is the maximum image of RGB.

In [51]:
transmission_for_Saturation = transmission.copy()
print(transmission_for_Saturation.dtype)

float64


In [52]:
print(transmission_for_Saturation)

[[0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 [0.29764706 0.29764706 0.29764706 ... 0.35058824 0.35058824 0.35411765]
 ...
 [0.65764706 0.65764706 0.65764706 ... 0.79882353 0.79882353 0.79882353]
 [0.65764706 0.65764706 0.66470588 ... 0.79882353 0.79882353 0.79882353]
 [0.66117647 0.66117647 0.66117647 ... 0.79882353 0.79882353 0.79882353]]


In [53]:
transmission_for_Saturation = transmission_for_Saturation - 1
print(transmission_for_Saturation)

[[-0.70235294 -0.70235294 -0.70235294 ... -0.64941176 -0.64941176
  -0.64588235]
 [-0.70235294 -0.70235294 -0.70235294 ... -0.64941176 -0.64941176
  -0.64588235]
 [-0.70235294 -0.70235294 -0.70235294 ... -0.64941176 -0.64941176
  -0.64588235]
 ...
 [-0.34235294 -0.34235294 -0.34235294 ... -0.20117647 -0.20117647
  -0.20117647]
 [-0.34235294 -0.34235294 -0.33529412 ... -0.20117647 -0.20117647
  -0.20117647]
 [-0.33882353 -0.33882353 -0.33882353 ... -0.20117647 -0.20117647
  -0.20117647]]


In [54]:
#comprobando que V es el maximo de RGB
print(channel_V[0][0])
print(img_resized[0][0])

220
[220 215 213]


In [55]:
maximumRGB = channel_V
equation_1 = A_ * transmission_for_Saturation
equation_2 = equation_1/maximumRGB

In [56]:
print(maximumRGB.shape)
print(equation_1.shape)

(480, 705)
(480, 705)


In [57]:
print(equation_2.dtype)

float64


In [58]:
channel_SFloat = np.float64(channel_S)

In [59]:
recoSaturation = channel_SFloat * (1/(1+equation_2))
recoSaturation = np.uint8(recoSaturation)

In [60]:
cv2.imshow('channel S Retrieved', recoSaturation)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Comparacion S y S recovered

In [61]:
cv2.imshow('channel S Real', channelReal_S) #canal a donde se quiere llegar (Y)
cv2.imshow('channel S hazy', channel_S)
cv2.imshow('channel S Retrieved', recoSaturation)

recoSaturationInv = abs(255-recoSaturation)
cv2.imshow('channel S Retrieved Inverso', recoSaturationInv)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Result

In [62]:

mergedDehazing = cv2.merge([channel_H,recoSaturation,recoValue])
bgrimg = cv2.cvtColor(mergedDehazing, cv2.COLOR_HSV2BGR)



In [63]:
cv2.imshow("Image Ground Truth", img_resizedReal)
cv2.imshow("Hazy Image", img_resized)
cv2.imshow("Dezahing Image ", bgrimg)
cv2.waitKey (0)
cv2.destroyAllWindows()